apiVersion: performance.openshift.io/v2
kind: PerformanceProfile
metadata:
  name: cnv-sriov-profile 
spec:
  cpu:
    isolated: "4-19,24-39"
    reserved: "0-3,20-23"
  hugepages:
    defaultHugepagesSize: "1G"
    pages:
    - size: "1G"
      count: 16 
    - size: "2M"
      count: 512
  realTimeKernel:
    enabled: true 
  nodeSelector:
    node-role.kubernetes.io/master: "" 
  machineConfigPoolSelector:
    pools.operator.machineconfiguration.openshift.io/master: ""
